#!/bin/sh
IMG=$1
FOLDER=$2

echo "Create folder"
mkdir -p source/images/posts/$FOLDER

echo "Creating images"
echo " - small"
convert $IMG -resize  600 source/images/posts/$FOLDER/small.png
echo " - medium"
convert $IMG -resize 1000 source/images/posts/$FOLDER/mid.png
echo " - large"
convert $IMG -resize 1200 source/images/posts/$FOLDER/large.png
echo " - grays"
convert $IMG -grayscale Rec709Luminance source/images/posts/$FOLDER/gray.png

echo "Optimize images"
echo " - small"
optipng source/images/posts/$FOLDER/small.png
echo " - medium"
optipng source/images/posts/$FOLDER/mid.png
echo " - large"
optipng source/images/posts/$FOLDER/large.png
echo " - grays"
optipng source/images/posts/$FOLDER/gray.png
